version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
      - shared-data:/app/shared
    environment:
      - STREAMLIT_SERVER_PORT=8501

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8502:8501"  # map server's port 8501 to host's port 8502
    volumes:
      - ./server:/app
      - shared-data:/app/shared
    environment:
      - STREAMLIT_SERVER_PORT=8502

volumes:
  shared-data:
